Update BookController.java
root cause

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Ambiguous mapping found. Cannot map 'bookController' bean method 
public org.springframework.hateoas.Resources<devfun.bookstore.rest.domain.BookResource> devfun.bookstore.rest.controller.BookController.getBooks(org.springframework.ui.Model)
to {[/books],methods=[GET],params=[],headers=[],consumes=[],produces=[],custom=[]}: There is already 'bookController' bean method
public java.util.List<devfun.bookstore.common.domain.Book> devfun.bookstore.rest.controller.BookController.getBooks() mapped.